FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.4

COPY config/elasticsearch/logging.yml /usr/share/elasticsearch/config/
COPY config/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/